<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('cities')->delete();
      DB::table('cities')->insert([
          array('province_id' => '1', 'city' => 'Banda Aceh', 'slug' => 'banda-aceh'),
          array('province_id' => '1', 'city' => 'Langsa', 'slug' => 'langsa'),
          array('province_id' => '1', 'city' => 'Lhokseumawe', 'slug' => 'lhokseumawe'),
          array('province_id' => '1', 'city' => 'Meulaboh', 'slug' => 'meulaboh'),
          array('province_id' => '1', 'city' => 'Sabang', 'slug' => 'sabang'),
          array('province_id' => '1', 'city' => 'Subulussalam', 'slug' => 'subulussalam'),
          array('province_id' => '2', 'city' => 'Denpasar', 'slug' => 'denpasar'),
          array('province_id' => '3', 'city' => 'Pangkal Pinang', 'slug' => 'pangkal-pinang'),
          array('province_id' => '4', 'city' => 'Cilegon', 'slug' => 'cilegon'),
          array('province_id' => '4', 'city' => 'Serang', 'slug' => 'serang'),
          array('province_id' => '4', 'city' => 'Tanggerang Selatan', 'slug' => 'tanggerang-selatan'),
          array('province_id' => '4', 'city' => 'Tanggerang', 'slug' => 'tanggerang'),
          array('province_id' => '5', 'city' => 'Bengkulu', 'slug' => 'bengkulu'),
          array('province_id' => '6', 'city' => 'Gorontalo', 'slug' => 'gorontalo'),
          array('province_id' => '7', 'city' => 'Jakarta Barat', 'slug' => 'jakarta-barat'),
          array('province_id' => '7', 'city' => 'Jakarta Pusat', 'slug' => 'jakarta-pusat'),
          array('province_id' => '7', 'city' => 'Jakarta Timur', 'slug' => 'jakarta-timur'),
          array('province_id' => '7', 'city' => 'Jakarta Utara', 'slug' => 'jakarta-utara'),
          array('province_id' => '8', 'city' => 'Sungai Penuh', 'slug' => 'sungai-penuh'),
          array('province_id' => '8', 'city' => 'Jambi', 'slug' => 'jambi'),
          array('province_id' => '9', 'city' => 'Bandung', 'slug' => 'bandung'),
          array('province_id' => '9', 'city' => 'Bekasi', 'slug' => 'bekasi'),
          array('province_id' => '9', 'city' => 'Bogor', 'slug' => 'bogor'),
          array('province_id' => '9', 'city' => 'Cimahi', 'slug' => 'cimahi'),
          array('province_id' => '9', 'city' => 'Cirebon', 'slug' => 'cirebon'),
          array('province_id' => '9', 'city' => 'Depok', 'slug' => 'depok'),
          array('province_id' => '9', 'city' => 'Sukabumi', 'slug' => 'sukabumi'),
          array('province_id' => '9', 'city' => 'Tasikmalaya', 'slug' => 'tasikmalaya'),
          array('province_id' => '9', 'city' => 'Banjar', 'slug' => 'banjar'),
          array('province_id' => '10', 'city' => 'Magelang', 'slug' => 'magelang'),
          array('province_id' => '10', 'city' => 'Perkalongan', 'slug' => 'perkalongan'),
          array('province_id' => '10', 'city' => 'Purwokerto', 'slug' => 'purwokerto'),
          array('province_id' => '10', 'city' => 'Salatiga', 'slug' => 'salatiga'),
          array('province_id' => '10', 'city' => 'Semarang', 'slug' => 'semarang'),
          array('province_id' => '10', 'city' => 'Surakarta', 'slug' => 'surakarta'),
          array('province_id' => '10', 'city' => 'Tegal', 'slug' => 'tegal'),
          array('province_id' => '11', 'city' => 'Batu', 'slug' => 'batu'),
          array('province_id' => '11', 'city' => 'Blitar', 'slug' => 'blitar'),
          array('province_id' => '11', 'city' => 'Kediri', 'slug' => 'kediri'),
          array('province_id' => '11', 'city' => 'Madiun', 'slug' => 'madiun'),
          array('province_id' => '11', 'city' => 'Malang', 'slug' => 'malang'),
          array('province_id' => '11', 'city' => 'Mojokerto', 'slug' => 'mojokerto'),
          array('province_id' => '11', 'city' => 'Pasuruan', 'slug' => 'pasuruan'),
          array('province_id' => '11', 'city' => 'Probolingo', 'slug' => 'probolinggo'),
          array('province_id' => '11', 'city' => 'Surabaya', 'slug' => 'surabaya'),
          array('province_id' => '12', 'city' => 'Pontianak', 'slug' => 'pontianak'),
          array('province_id' => '12', 'city' => 'Singkawang', 'slug' => 'singkawang'),
          array('province_id' => '13', 'city' => 'Banjarbaru', 'slug' => 'banjarbaru'),
          array('province_id' => '13', 'city' => 'Banjarmasin', 'slug' => 'banjarmasin'),
          array('province_id' => '14', 'city' => 'Palangkaraya', 'slug' => 'palangkaraya'),
          array('province_id' => '15', 'city' => 'Balikpapan', 'slug' => 'balikpapan'),
          array('province_id' => '15', 'city' => 'Bontang', 'slug' => 'bontang'),
          array('province_id' => '15', 'city' => 'Samarinda', 'slug' => 'samarinda'),
          array('province_id' => '15', 'city' => 'Tenggarong', 'slug' => 'tenggarong'),
          array('province_id' => '15', 'city' => 'Berau', 'slug' => 'berau'),
          array('province_id' => '16', 'city' => 'Tarakan', 'slug' => 'tarakan'),
          array('province_id' => '17', 'city' => 'Batam', 'slug' => 'batam'),
          array('province_id' => '17', 'city' => 'Tanjung Pinang', 'slug' => 'tanjung-pinang'),
          array('province_id' => '18', 'city' => 'Bandar Lampung', 'slug' => 'bandar-lampung'),
          array('province_id' => '18', 'city' => 'Kota Bumi', 'slug' => 'kota-bumi'),
          array('province_id' => '18', 'city' => 'Liwa', 'slug' => 'liwa'),
          array('province_id' => '18', 'city' => 'Metro', 'slug' => 'metro'),
          array('province_id' => '19', 'city' => 'Ternate', 'slug' => 'ternate'),
          array('province_id' => '19', 'city' => 'Tidore Kepulauan', 'slug' => 'tidore-kepulauan'),
          array('province_id' => '20', 'city' => 'Ambol', 'slug' => 'ambol'),
          array('province_id' => '20', 'city' => 'Tual', 'slug' => 'tual'),
          array('province_id' => '21', 'city' => 'Bima', 'slug' => 'bima'),
          array('province_id' => '21', 'city' => 'Mataram', 'slug' => 'mataram'),
          array('province_id' => '22', 'city' => 'Kupang', 'slug' => 'kupang'),
          array('province_id' => '23', 'city' => 'Sorong', 'slug' => 'sorong'),
          array('province_id' => '24', 'city' => 'Jaya Pura', 'slug' => 'jaya-pura'),
          array('province_id' => '25', 'city' => 'Dumai', 'slug' => 'dumai'),
          array('province_id' => '25', 'city' => 'Pekan Baru', 'slug' => 'pekan-baru'),
          array('province_id' => '26', 'city' => 'Makassar', 'slug' => 'makassar'),
          array('province_id' => '26', 'city' => 'Palopo', 'slug' => 'palopo'),
          array('province_id' => '26', 'city' => 'Parepare', 'slug' => 'pare-pare'),
          array('province_id' => '27', 'city' => 'Palu', 'slug' => 'palu'),
          array('province_id' => '28', 'city' => 'Bau-Bau', 'slug' => 'bau-bau'),
          array('province_id' => '28', 'city' => 'Kendari', 'slug' => 'kendari'),
          array('province_id' => '29', 'city' => 'Bitung', 'slug' => 'bitung'),
          array('province_id' => '29', 'city' => 'Kotamobagu', 'slug' => 'kotamagu'),
          array('province_id' => '29', 'city' => 'Manado', 'slug' => 'manado'),
          array('province_id' => '29', 'city' => 'Tomohon', 'slug' => 'tomohon'),
          array('province_id' => '30', 'city' => 'Bukittinggi', 'slug' => 'bukittinggi'),
          array('province_id' => '30', 'city' => 'Padang', 'slug' => 'padang'),
          array('province_id' => '30', 'city' => 'Padangpanjang', 'slug' => 'padangpanjang'),
          array('province_id' => '30', 'city' => 'Pariaman', 'slug' => 'pariaman'),
          array('province_id' => '30', 'city' => 'Payakumbuh', 'slug' => 'payakumbuh'),
          array('province_id' => '30', 'city' => 'Sawahlunto', 'slug' => 'sawahlunto'),
          array('province_id' => '30', 'city' => 'Solok', 'slug' => 'solok'),
          array('province_id' => '31', 'city' => 'Lubuklinggau', 'slug' => 'lubuklinggau'),
          array('province_id' => '31', 'city' => 'Pagaralam', 'slug' => 'pagaralam'),
          array('province_id' => '31', 'city' => 'palembang', 'slug' => 'palembang'),
          array('province_id' => '31', 'city' => 'Prabumulih', 'slug' => 'prambulih'),
          array('province_id' => '32', 'city' => 'Binjai', 'slug' => 'binjai'),
          array('province_id' => '32', 'city' => 'Medan', 'slug' => 'medan'),
          array('province_id' => '32', 'city' => 'Padang Sidempuan', 'slug' => 'padang-sidempuan'),
          array('province_id' => '32', 'city' => 'Pematangsiantar', 'slug' => 'pemantang-siantar'),
          array('province_id' => '32', 'city' => 'Sibolga', 'slug' => 'sibolga'),
          array('province_id' => '32', 'city' => 'Tanjungbalai', 'slug' => 'tanjungbalai'),
          array('province_id' => '32', 'city' => 'Tebingtinggi', 'slug' => 'tebingtingg'),
          array('province_id' => '33', 'city' => 'Yogyakarta', 'slug' => 'yogyakarta'),
       ]);
    }
}
